<?php

/**
* @file
* Contains varbase_email.module.
*/

/**
* Implements hook_theme().
*/

function varbase_email_theme($existing, $type, $theme, $path){
  $templates = $path . '/templates';

  $return['swiftmailer'] = [
   'template' => 'varbase_emails',
   'path' => $templates,
   'variables' => [
     'message' => [],
   ],
   'mail theme' => TRUE,
  ];
  return $return;
}


/**
* Prepares variables for varbase_emails.html.twig templates.
* Implements hook_preprocess_HOOK() for field templates.
*/
function varbase_email_preprocess_swiftmailer(&$variables){
  $theme_id = \Drupal::config('system.theme')->get('default');
  $site_config = \Drupal::config('system.site');

  $request = \Drupal::request();
  $host = $request->getSchemeAndHttpHost();
  // Default we use the logo image.
  $variables['logo'] = $host . theme_get_setting('logo.url', $theme_id);


  if ($site_config) {
    $variables['site_link'] = TRUE;
    $variables['site_name'] = $site_config->get('name');
    if ($site_config->get('slogan')) {
      $variables['site_slogan'] = $site_config->get('slogan');
    }
  }else{
    $variables['site_name'] = t('Varbase');
    $variables['site_slogan'] = '"' . t('The Ultimate Drupal 8 CMS Starter Kit') . '"';
  }

  if ($user = user_load_by_mail($variables['message']['to'])) {
    $message = $variables['message'];
    $options = [
      'langcode' => $message['langcode'],
    ];

    $replace = [
      '%display_name' => $user->getDisplayName(),
    ];
    $variables['heading'] = t('Hi %display_name', $replace, $options);
  }
}
