<?php

/**
 * @file
 * Install, update and uninstall functions for the Varbase email module.
 */

use Vardot\Installer\ModuleInstallerFactory;

/**
 * Implements hook_install().
 */
function varbase_email_install() {

  // Processer for install: in varbase_email.info.yml file.
  // ---------------------------------------------------------------------------.
  ModuleInstallerFactory::installList('varbase_email');

}
